### ISSUE TITLE
TRITO item_note_type.yaml

### ISSUE THREAD

**Issue by chrnelson** [kivilahtio/koha-migration-toolbox-config#28]
Olisiko mahdollista pudottaa pois kaikki regular item houmaustukset, paitsi tiettyyn kokoelmaan kuuluvat. Meillä on noin 72000 nidehuomautusta ja haluaisimme ottaa vain QLYCEI (nyk OH-Lycei) -kokoelmaan kuuluvien niteiden huomautukset mukaan Kohaan.

**Comment by ghost** [comment]
Ei nykyiseltään, mutta jos Kohassa nämä löytyy esim. hyllypaikan tai nidetyypin mukaan niin ne voi SQL:llä melko helposti ottaa pois konversion jälkeen.

**Comment by ghost** [comment]
Tällä aikataululla jätetään Kohassa tehtäväksi, suljen siis tämän tiketin.
